package cli

import "testing"

// TestShimInternalCommandRegistered asserts that the `__shim` hidden
// subcommand is wired into the root. The `.ps1` wrappers generated by
// chpwd on Windows (issue #89) invoke `jitenv.exe __shim <cmd> @args`,
// so a missing registration would silently break every wrapped command
// on PowerShell. Coverage here is "find the command + check its flags";
// actually running it would call shim.Main which calls os.Exit — that
// belongs in a subprocess integration test, not a unit test.
func TestShimInternalCommandRegistered(t *testing.T) {
	root := newRoot()
	c, _, err := root.Find([]string{"__shim", "npm", "install"})
	if err != nil {
		t.Fatalf("root.Find(__shim): %v", err)
	}
	if c.Use == "" || c.Name() != "__shim" {
		t.Fatalf("expected __shim subcommand, got %q (use=%q)", c.Name(), c.Use)
	}
	if !c.Hidden {
		t.Error("__shim subcommand should be hidden")
	}
	if !c.DisableFlagParsing {
		// Wrapped commands accept arbitrary args, including flags
		// (`npm install --save-dev foo`). Without DisableFlagParsing
		// cobra would try to interpret them as jitenv flags.
		t.Error("__shim subcommand should disable flag parsing so it forwards user flags verbatim")
	}
}
