//go:build windows

package chpwd

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/BurntSushi/toml"

	"github.com/gv/jitenv/internal/agent"
	"github.com/gv/jitenv/internal/config"
)

// writeConfig encodes cfg to a TOML file at path. Helper for the
// Windows-specific reconcile tests below.
func writeConfig(t *testing.T, path string, cfg config.Config) {
	t.Helper()
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := toml.NewEncoder(f).Encode(&cfg); err != nil {
		f.Close()
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
}

// TestReconcileCreatesPs1Wrappers is the headline test for issue #89:
// running chpwd from a cwd that matches a cwd_glob mapping must
// populate the wrap dir with `<cmd>.ps1` files, not bare-named
// symlinks. The body of each wrapper must invoke jitenv.exe with the
// explicit __shim subcommand so cmd/jitenv/main.go dispatches
// unambiguously.
func TestReconcileCreatesPs1Wrappers(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("LOCALAPPDATA", filepath.Join(tmp, "localapp"))
	cfgPath := filepath.Join(tmp, "config.toml")
	t.Setenv("JITENV_CONFIG", cfgPath)

	projectDir := filepath.Join(tmp, "project")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeConfig(t, cfgPath, config.Config{
		Version: 1,
		Mappings: []config.Mapping{{
			CwdGlob:  filepath.ToSlash(projectDir),
			Commands: []string{"npm", "node"},
		}},
	})

	pid := os.Getpid()
	paths, _ := agent.DefaultPaths()
	wrapDir := paths.ShellWrapDir(pid)

	if err := Run([]string{strconv.Itoa(pid), "", projectDir}); err != nil {
		t.Fatalf("Run: %v", err)
	}

	for _, cmd := range []string{"npm", "node"} {
		wrap := filepath.Join(wrapDir, cmd+".ps1")
		b, err := os.ReadFile(wrap)
		if err != nil {
			t.Fatalf("expected wrapper %s: %v", wrap, err)
		}
		body := string(b)
		if !strings.Contains(body, "# Generated by jitenv chpwd") {
			t.Errorf("wrapper %s missing header marker:\n%s", wrap, body)
		}
		if !strings.Contains(body, "__shim "+cmd+" @args") {
			t.Errorf("wrapper %s missing __shim invocation:\n%s", wrap, body)
		}
		if !strings.Contains(body, "exit $LASTEXITCODE") {
			t.Errorf("wrapper %s missing exit propagation:\n%s", wrap, body)
		}
	}
}

// TestReconcileIsNoopOnRepeat verifies the content-based idempotency
// of the Windows reconcile path. Running Run twice with the same
// config + cwd must leave the wrapper file's mtime unchanged on the
// second call — that's the load-bearing property the per-prompt hook
// relies on.
func TestReconcileIsNoopOnRepeat(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("LOCALAPPDATA", filepath.Join(tmp, "localapp"))
	cfgPath := filepath.Join(tmp, "config.toml")
	t.Setenv("JITENV_CONFIG", cfgPath)

	projectDir := filepath.Join(tmp, "project")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeConfig(t, cfgPath, config.Config{
		Version: 1,
		Mappings: []config.Mapping{{
			CwdGlob:  filepath.ToSlash(projectDir),
			Commands: []string{"npm"},
		}},
	})

	pid := os.Getpid()
	paths, _ := agent.DefaultPaths()
	wrapDir := paths.ShellWrapDir(pid)

	if err := Run([]string{strconv.Itoa(pid), "", projectDir}); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	wrap := filepath.Join(wrapDir, "npm.ps1")

	// Force-bump the wrapper's mtime to a known past value so that
	// any rewrite by the second Run is unambiguous (the new mtime
	// would be ~now).
	past := time.Now().Add(-5 * time.Second).Truncate(time.Second)
	if err := os.Chtimes(wrap, past, past); err != nil {
		t.Fatal(err)
	}
	// Bump the config mtime so Run doesn't take the cheap short-
	// circuit fast-path (which would skip reconcile entirely — a
	// stronger property than the no-op-rewrite we want to verify
	// here). createWrapper's content-equality check should then
	// notice the file is already correct and leave it alone.
	future := time.Now().Add(5 * time.Second)
	if err := os.Chtimes(cfgPath, future, future); err != nil {
		t.Fatal(err)
	}
	if err := Run([]string{strconv.Itoa(pid), projectDir, projectDir}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	st2, err := os.Stat(wrap)
	if err != nil {
		t.Fatalf("stat after second Run: %v", err)
	}
	// FAT/exFAT have 2s mtime granularity, NTFS is 100ns; allow a
	// 1s tolerance against the explicit `past`.
	if delta := st2.ModTime().Sub(past); delta > time.Second || delta < -time.Second {
		t.Errorf("expected second Run to leave wrapper mtime≈%v (no rewrite); got %v (delta=%v)",
			past, st2.ModTime(), delta)
	}
}

// TestReconcileRemovesUnmappedWrapper verifies that when the desired
// command set shrinks (or the user leaves the mapped cwd), the now-
// orphaned wrapper file is removed.
func TestReconcileRemovesUnmappedWrapper(t *testing.T) {
	tmp := t.TempDir()
	t.Setenv("LOCALAPPDATA", filepath.Join(tmp, "localapp"))
	cfgPath := filepath.Join(tmp, "config.toml")
	t.Setenv("JITENV_CONFIG", cfgPath)

	projectDir := filepath.Join(tmp, "project")
	otherDir := filepath.Join(tmp, "other")
	for _, d := range []string{projectDir, otherDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	writeConfig(t, cfgPath, config.Config{
		Version: 1,
		Mappings: []config.Mapping{{
			CwdGlob:  filepath.ToSlash(projectDir),
			Commands: []string{"npm"},
		}},
	})

	pid := os.Getpid()
	paths, _ := agent.DefaultPaths()
	wrapDir := paths.ShellWrapDir(pid)

	// First call inside the mapped dir: npm.ps1 is created.
	if err := Run([]string{strconv.Itoa(pid), "", projectDir}); err != nil {
		t.Fatalf("first Run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(wrapDir, "npm.ps1")); err != nil {
		t.Fatalf("expected npm.ps1 after first Run: %v", err)
	}

	// Bump mtime so reconcile actually runs again, then walk out to an
	// unmapped dir. The npm.ps1 must be removed.
	future := time.Now().Add(5 * time.Second)
	if err := os.Chtimes(cfgPath, future, future); err != nil {
		t.Fatal(err)
	}
	if err := Run([]string{strconv.Itoa(pid), projectDir, otherDir}); err != nil {
		t.Fatalf("second Run: %v", err)
	}
	if _, err := os.Stat(filepath.Join(wrapDir, "npm.ps1")); err == nil {
		t.Error("expected npm.ps1 to be removed after leaving mapped dir")
	}
}

// TestIsOursContentBased verifies the IsOurs predicate independently:
// it must accept a freshly-written wrapper, reject a foreign file, and
// reject a wrapper baked against a different jitenv path (so a moved
// binary triggers a rewrite).
func TestIsOursContentBased(t *testing.T) {
	dir := t.TempDir()
	exe := filepath.Join(dir, "jitenv.exe")

	// Foreign file: not a wrapper jitenv wrote.
	foreign := filepath.Join(dir, "foreign.ps1")
	if err := os.WriteFile(foreign, []byte("# some other tool\nWrite-Host hi\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if ok, _ := isOurs(foreign, exe); ok {
		t.Error("isOurs accepted a foreign file")
	}

	// Wrapper baked against the right jitenv: accepted.
	good := filepath.Join(dir, "npm.ps1")
	if err := os.WriteFile(good, []byte(wrapperContent("npm", exe)), 0o600); err != nil {
		t.Fatal(err)
	}
	if ok, err := isOurs(good, exe); err != nil || !ok {
		t.Errorf("isOurs rejected a freshly-written wrapper: ok=%v err=%v", ok, err)
	}

	// Wrapper baked against a different jitenv path: rejected so
	// reconcile rewrites.
	stale := filepath.Join(dir, "stale.ps1")
	otherExe := filepath.Join(dir, "elsewhere", "jitenv.exe")
	if err := os.WriteFile(stale, []byte(wrapperContent("npm", otherExe)), 0o600); err != nil {
		t.Fatal(err)
	}
	if ok, _ := isOurs(stale, exe); ok {
		t.Error("isOurs accepted a wrapper baked against a different jitenv path")
	}
}

// TestWrapperContentQuotesCmd is the regression for security #109: the
// command name interpolated into the .ps1 body must be PowerShell-
// single-quoted, otherwise a config-authored command containing `;`,
// `|`, `$(…)`, backtick, or whitespace breaks out into active syntax
// and runs at the privilege of every interactive shell that enters
// the mapped directory.
func TestWrapperContentQuotesCmd(t *testing.T) {
	const exe = `C:\Program Files\jitenv\jitenv.exe`
	cases := []struct {
		cmd  string
		want string
	}{
		{"npm", "& 'C:\\Program Files\\jitenv\\jitenv.exe' __shim 'npm' @args"},
		{"npm; Invoke-WebRequest evil", "& 'C:\\Program Files\\jitenv\\jitenv.exe' __shim 'npm; Invoke-WebRequest evil' @args"},
		{"weird's name", "& 'C:\\Program Files\\jitenv\\jitenv.exe' __shim 'weird''s name' @args"},
		{"$(Get-Process)", "& 'C:\\Program Files\\jitenv\\jitenv.exe' __shim '$(Get-Process)' @args"},
	}
	for _, c := range cases {
		got := wrapperContent(c.cmd, exe)
		if !strings.Contains(got, c.want) {
			t.Errorf("wrapperContent(%q, exe) body missing %q\n--- got ---\n%s", c.cmd, c.want, got)
		}
	}
}

// TestPsSingleQuoteEscaping is the regression for the path-with-quote
// edge case. PowerShell's only literal-string escape is doubling a
// single quote; missing this would generate a syntactically invalid
// `.ps1` (PowerShell would parse the embedded ' as a string
// terminator).
func TestPsSingleQuoteEscaping(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{`C:\Program Files\jitenv.exe`, `'C:\Program Files\jitenv.exe'`},
		{`C:\weird's path\jitenv.exe`, `'C:\weird''s path\jitenv.exe'`},
		{`''`, `''''''`},
	}
	for _, c := range cases {
		if got := psSingleQuote(c.in); got != c.want {
			t.Errorf("psSingleQuote(%q) = %q; want %q", c.in, got, c.want)
		}
	}
}
