//go:build windows

package chpwd

import (
	"fmt"
	"os"
	"strings"
)

// wrapperExt is the extension PowerShell honours for natively-resolved
// commands on %PATH%. The chpwd wrap dir is prepended to %PATH% by the
// PowerShell hook (issue #90), so a `.ps1` file named after a command
// is picked up before the real binary further down the path.
const wrapperExt = ".ps1"

// wrapperFileName returns the on-disk filename for a wrapper command.
// On Windows that's `<cmd>.ps1` — PowerShell's `Get-Command` /
// `commandLookup` honours %PATHEXT% (which includes `.PS1` by default)
// when resolving a bare name typed at the prompt.
func wrapperFileName(cmd string) string {
	return cmd + wrapperExt
}

// wrapperContent returns the body of the `.ps1` wrapper for command
// `cmd`. The script invokes the jitenv binary with the explicit
// `__shim` subcommand (so the dispatch in cmd/jitenv/main.go doesn't
// have to play argv[0] games on Windows), splats the remaining args
// via PowerShell's `@args`, and propagates the child's exit code so
// callers observe the wrapped program's status rather than
// PowerShell's.
//
// `jitenvExe` is the absolute path to jitenv.exe captured at chpwd
// time. Single-quoting in PowerShell is fully literal — no expansion,
// no escape sequences — except that an embedded single quote must be
// doubled. `psSingleQuote` handles that.
func wrapperContent(cmd, jitenvExe string) string {
	return "# Generated by jitenv chpwd. Do not edit; removed when this shell exits.\r\n" +
		"& " + psSingleQuote(jitenvExe) + " __shim " + psSingleQuote(cmd) + " @args\r\n" +
		"exit $LASTEXITCODE\r\n"
}

// psSingleQuote wraps s in PowerShell single-quotes, doubling any
// embedded single quote so the result is a syntactically valid literal
// string. The PowerShell rule is "inside '...' the only escape is ”
// for a literal '" — no backslash processing, no variable expansion.
func psSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// createWrapper installs (or refreshes) a `.ps1` wrapper for `cmd` at
// `wrapPath`. The file is rewritten only when its contents differ from
// the canonical body (cheap no-op when the desired set is unchanged).
// Mode 0600 matches the rest of the per-shell tree; on Windows the
// mode bits map onto the user's ACL, which is enough for the wrap dir
// (which already lives under %LOCALAPPDATA%\jitenv\... — a per-user
// path).
func createWrapper(wrapPath, cmd, jitenvExe string) error {
	desired := wrapperContent(cmd, jitenvExe)
	if existing, err := os.ReadFile(wrapPath); err == nil && string(existing) == desired {
		return nil
	}
	if err := os.WriteFile(wrapPath, []byte(desired), 0o600); err != nil {
		return fmt.Errorf("write wrapper %s: %w", wrapPath, err)
	}
	return nil
}

// isOurs returns true if the file at wrapPath looks like a wrapper
// jitenv itself wrote. The check is content-based: the first line of
// every generated wrapper is the "Generated by jitenv chpwd" marker,
// and the body invokes the current jitenv.exe. A foreign file in the
// dir (highly unlikely — the dir is jitenv-only — but a defensive
// check anyway) returns false so reconcile doesn't claim it.
//
// We don't require byte-for-byte equality with wrapperContent(cmd,
// jitenvExe); rewriting with stale path is the desired action when
// jitenv has moved on disk, so a `true` result for "header present,
// invocation line mentions some jitenv.exe" is enough.
func isOurs(wrapPath, jitenvExe string) (bool, error) {
	b, err := os.ReadFile(wrapPath)
	if err != nil {
		return false, err
	}
	s := string(b)
	if !strings.HasPrefix(s, "# Generated by jitenv chpwd") {
		return false, nil
	}
	// Belt-and-suspenders: ensure the script invokes the right binary
	// before we treat it as a no-op candidate. createWrapper rewrites
	// otherwise.
	return strings.Contains(s, psSingleQuote(jitenvExe)), nil
}
